data_api/urls.py
from django.urls import path
from django.conf.urls import url, include


from . import views

app_name = "data_api"

urlpatterns = [
    path('', views.index, name = 'index'),

]

data_projects/urls.py
from django.urls import path
from rest_framework import routers
from . import views_api
from django.conf.urls import url, include

app_name = "data_projects"

router = routers.DefaultRouter()
router.register('research_projects', views_api.ResearchProjectViewSet)
router.register('research_project_ouputs', views_api.ResearchProjectOutputViewSet)
router.register('research_project_grant_application_reviews', views_api.ResearchProjectGrantApplicationReviewViewSet)
router.register('research_project_grant_application_reviewer_scores', views_api.ResearchProjectGrantApplicationReviewerScoreViewSet)

urlpatterns = [
    path("/v1/", include(router.urls)),
]

main/urls.py
from django.urls import path
from django.conf.urls import url, include


from . import views
from . import views_reports

app_name = "main"

urlpatterns = [
    path('', views.index, name = 'index'),
    path('data-api', views.data_api, name = "data_api"),
    path('metadata', views.metadata, name = "metadata"),
    path('news/<int:news_item_id>/', views.news_item, name='news_item'),
    path('task-note-edit/<int:id>', views.edit_task_or_note, name = "task_note_edit"),
    path('metadata/<int:asset_id>/', views.metadata_detail, name = "metadata_detail"),
    path('data-onboarding', views.dataonboarding, name = "data_onboarding"),
    path('resources', views.resources, name = "resources"),
    path('data-requests', views.data_requests, name = "data_requests"),
    path('data-projects', views.data_projects, name='data_projects'),
    path('data-project-review', views.data_project_review, name='data_project_review'),
    path('apps-and-notebooks', views.apps_and_notebooks, name='apps_and_notebooks'),
    path('data-projects/<int:data_project_id>/', views.data_projects_detail, name = "projects_detail"),
    path('data-project-review-detail/<int:data_project_id>/', views.data_projects_review_detail, name = "projects_review"),
    path('forms', views.forms, name = "forms"),
    path('submit-data-request', views.submit_data_request, name = "submit_data_request"),
    url(r'^data-requests/(?P<var1>\d+)/$', views.DataRequestDetailView.as_view(), name = "main"),
    url(r'^data-project-output/(?P<var1>\d+)/$', views.DataProjectOutputDetailView.as_view(), name = "main"),
    path('question/submit', views.NoteFormView.as_view(), name='question'),
    path('data-project-output-note', views.DataProjectOutputNoteFormView.as_view(), name='dpo_submit'),
    path('answer/submit', views.TaskFormView.as_view(), name='answer'),
    path('status/change', views.UpdateStatusFormView.as_view(), name='status_change'),
    path("thanks",views.thanks),
    path('profile', views.user_profile),
    path("assets-report", views_reports.assets_report),
    path("users-report", views_reports.users_report),


]

maple/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_swagger.views import get_swagger_view
from django.conf.urls import url
from markdownx import urls as markdownx

schema_view = get_swagger_view(title='CIDA Data API')

admin.site.site_header = 'Maple Administration'

urlpatterns = [
    url(r'^markdownx/', include('markdownx.urls')),
    path('swagger/', schema_view),
    path('admin/', admin.site.urls),
    path('maple/', include('main.urls')),
    path('news-items-api', include('news_items.urls')),
    path('research-projects-api', include('data_projects.urls')),
    path('data-assets-api', include('data_assets.urls')),
    path('requests-api', include('projects.urls')),
    path('accounts-api', include('accounts.urls')),
    path('notes-and-tasks-api', include('notes_and_tasks.urls')),
    path('apps-and-notebooks-api', include('apps_and_notebooks.urls')),
    path('accounts/', include('django.contrib.auth.urls')),


]

apps_and_notebooks/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime

class AppOrNotebook(models.Model):
    created_by = models.ForeignKey(User, related_name="app_or_notebook", on_delete=models.CASCADE,
                              null=True)
    title = models.CharField(max_length=255)
    release_date = models.DateField(default=datetime.now)
    description = models.TextField()
    location = models.CharField(max_length=255)
    tags = models.CharField(max_length = 255)
    version = models.FloatField()
    type = models.CharField(max_length = 50)

    def __str__(self):
        return self.title

data_api/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime



class DataAPI(models.Model):
    managed_by = models.ForeignKey(User, related_name="data_api", on_delete=models.CASCADE,
                              null=True)
    title = models.CharField(max_length=255)
    version = models.FloatField()
    usage_notes = models.TextField()
    location = models.CharField(max_length=255)
    type = models.CharField(max_length = 255)
    formats_supported = models.CharField(max_length = 255)

    def __str__(self):
        return self.title


class ChangeLog(models.Model):
    data_api = models.ForeignKey(DataAPI, on_delete=models.CASCADE, null = True, blank = True)
    change_details = models.TextField()
    change_date = models.DateField(default=datetime.now, blank=True)
    change_made_by = models.ForeignKey(User, related_name="change_log", on_delete=models.CASCADE,
                              null=True)

data_projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count
from markdownx.models import MarkdownxField
from data_assets.models import DataAsset

APPLICATION_STATUS_CHOICES = (
    ("Under review", "Under review"),
    ("Reviewed", "Reviewed")
)

DATA_PROJECT_OUTPUT_TYPE_CHOICES = (
    ("Government report", "Government report"),
    ("Conference paper", "Conference paper"),
    ("Journal article", "Journal article"),
    ("App or notebook", "App or notebook")
)

DATA_PROJECT_INVESTIGATOR_CHOICES = (
    ("Lead investigator", "Lead investigator"),
    ("Investigator", "Investigator"),
    ("Co-investigator", "Co-investigator")
)


DATA_PROJECT_RESEARCH_TYPE_CHOICES = (
    ("Quality improvement only", "Quality improvement only"),
    ("Journal publication and quality improvement", "Journal publication and quality improvement"),
)


DATA_PROJECT_CURRENT_STATUS_CHOICES = (
    ("Active", "Active"),
    ("Not yet active", "Not yet active"),
    ("On hold", "On hold"),
)

DATA_PROJECT_OUTPUT_CURRENT_STATUS_CHOICES = (
    ("Scoping and preliminary analysis", "Scoping and preliminary analysis"),
    ("Awaiting approval to commence draft", "Awaiting approval to commence draft"),
    ("Preparing draft", "Preparing draft"),
    ("Awaiting internal approval for draft", "Awaiting internal approval for draft"),
    ("Submitted to journal or conference", "Submitted to journal or conference"),
    ("Accepted", "Accepted"),
    ("Completed", "Completed"),
)




class DataProject(models.Model):
    title = models.CharField(max_length = 255)
    summary = MarkdownxField()
    research_type = models.CharField(max_length = 200, choices = DATA_PROJECT_RESEARCH_TYPE_CHOICES)
    related_documentation_location = models.CharField(max_length = 100)
    working_folder = models.CharField(max_length = 200)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    internal_investigators_only = models.BooleanField(default = True)
    current_status = models.CharField(max_length = 100, choices = DATA_PROJECT_CURRENT_STATUS_CHOICES)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return self.title



class DataProjectInvestigator(models.Model):
    investigator_name = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    data_project = models.ForeignKey(DataProject, on_delete=models.CASCADE, null=True)
    role = models.CharField(max_length = 255, choices = DATA_PROJECT_INVESTIGATOR_CHOICES)

    def __str__(self):
        return self.investigator_name.username

class DataProjectOutput(models.Model):
    data_project = models.ForeignKey(DataProject, on_delete=models.CASCADE, null=True)
    output_title = models.CharField(max_length = 255)
    publication_or_conference_name = models.CharField(max_length = 255, null = True)
    related_documentation = models.CharField(max_length = 100)
    summary = MarkdownxField()
    working_folder = models.CharField(max_length = 200)
    start_date = models.DateField(null=True, blank=True)
    expected_release_date = models.DateField(null=True, blank=True)
    actual_release_date = models.DateField(null=True, blank=True)
    output_type = models.CharField(max_length = 200, choices = DATA_PROJECT_OUTPUT_TYPE_CHOICES)
    current_status = models.CharField(max_length = 100, choices = DATA_PROJECT_OUTPUT_CURRENT_STATUS_CHOICES)
    pubmed_id = models.CharField(max_length = 50, blank=True, null=True)
    data_assets = models.ManyToManyField(DataAsset, blank=True)

    def __str__(self):
        return self.output_title


class RequiredApproval(models.Model):
    approval_from = models.CharField(max_length = 100)
    approval_contact_name = models.CharField(max_length = 255)
    approval_start_date = models.DateField(null = True, blank = True)
    approval_end_date = models.DateField(null = True, blank = True)
    approval_reference = models.CharField(max_length = 100)
    data_project_output = models.ForeignKey(DataProjectOutput, on_delete=models.CASCADE, null=True, blank=True)
    data_project = models.ForeignKey(DataProject, on_delete=models.CASCADE, null=True, blank=True)
    granted = models.BooleanField(default = False)

    def __str__(self):
        return self.approval_from


class DataProjectOutputInvestigator(models.Model):
    investigator_name = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    project_output = models.ForeignKey(DataProjectOutput, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.investigator_name.username


class DataProjectGrantApplicationReview(models.Model):
    grant_id = models.CharField(max_length = 100)
    ci_prefix = models.CharField(max_length = 255)
    ci_name = models.CharField(max_length = 255)
    application_title = models.CharField(max_length = 255)
    administering_organisation = models.CharField(max_length = 255)
    lead_organisation = models.CharField(max_length = 255)
    status_of_review = models.CharField(max_length = 100, choices = APPLICATION_STATUS_CHOICES)

    def __str__(self):
        return self.grant_id


class DataProjectGrantApplicationReviewerScore(models.Model):
    reviewer_name = models.CharField(max_length = 255)
    application = models.ForeignKey(DataProjectGrantApplicationReview, on_delete=models.CASCADE, null=True)
    significance_score = models.FloatField()
    team_track_record_score = models.FloatField()
    translation_score =  models.FloatField()
    sustainability_score =  models.FloatField()
    comments = models.TextField()
    date_finalised = models.DateField(auto_now_add = True, blank=True, null=True)

    def __str__(self):
        return self.reviewer_name

main/models.py
from django.db import models

# Create your models here.

notes_and_tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import DataRequest
from data_projects.models import DataProjectOutput
from datetime import datetime


TYPE_CHOICES = (
    ("Note", "Note"),
    ("Task", "Task"),
)


class NoteOrTask(models.Model):
    type = models.CharField(max_length=200, choices = TYPE_CHOICES)
    allocated_to = models.ForeignKey(User, related_name = "user_allocated_to", on_delete = models.CASCADE, null = True, blank = True)
    created_by = models.ForeignKey(User, related_name = "user_created_by", on_delete = models.CASCADE, null = True)
    date_and_time_created = models.DateTimeField(auto_now_add=True)
    related_project_output = models.ForeignKey(DataProjectOutput,  on_delete=models.CASCADE, null = True, blank = True)
    related_request = models.ForeignKey(DataRequest, on_delete=models.CASCADE, null = True, blank = True)
    detail = models.TextField(null = True)
    date_due = models.DateField(default=datetime.now, blank=True)
    task_completed = models.BooleanField(default=False)
    restricted_to_admin_staff = models.BooleanField(default=False)

    class Meta:
        ordering = ["-date_and_time_created"]

main/forms.py
from django import forms
from django.forms import ModelForm
from projects.models import DataRequest
from data_assets.models import DataAssetBreach
from notes_and_tasks.models import NoteOrTask
from config import app_config


class ChangeTaskStatusForm(forms.Form):
    task_status = forms.ChoiceField(label = "Change status", choices = app_config.STATUS_CHOICES)


class UpdateStatusForm(forms.Form):
    updated_status = forms.ChoiceField(label = "Change status", choices = app_config.STATUS_CHOICES)


class TaskEditForm(ModelForm):
    class Meta:
        model = NoteOrTask
        fields = (
            'created_by',
            'detail',
            'allocated_to',
            'task_completed'
        )


class NoteEditForm(ModelForm):
    class Meta:
        model = NoteOrTask
        fields = (
            'detail',
        )



class DataRequestForm(ModelForm):
    class Meta:
        model = DataRequest
        fields = (
            'requestor_contact_name',
            'data_type',
            'detail',
            'related_documentation',
        )



class DataAssetBreachForm(forms.ModelForm):
	class Meta:
		model = DataAssetBreach
		fields = [
				"date_of_report",
			    "summary",
			    "description"
		]


class NoteForm(ModelForm):
    class Meta:
        model = NoteOrTask
        fields = (
                    'detail',
                )


class TaskForm(ModelForm):
    class Meta:
        model = NoteOrTask
        fields = (
            'allocated_to',
            'detail',
            'date_due',
        )

apps_and_notebooks/views.py
from django.shortcuts import render
from rest_framework import viewsets
from . import serializers
from . import models

class AppOrNotebookViewSet(viewsets.ModelViewSet):
    queryset = models.AppOrNotebook.objects.all()
    serializer_class = serializers.AppOrNotebookSerializer

data_api/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'data_api/index.html',)

main/templates/main/data-project-output-detail.html
{% extends "main/base.html" %}
{% load static %}
{% block metadata %}


<!-- MODAL 1 FOR ADDING NOTES  -->
<div id="modal1" class="modal">
   <div class="modal-content">
     <h5>Add a new note</h5>
     <form action="/maple/data-project-output-note" method="post">
        {% csrf_token %}
        {{ note_form }}
         <button class="btn-small #e65100 orange darken-4 waves-effect waves-light"  type="submit" name="action">Add note

       </button>
     </form>
   </div>
 </div>

 <!-- MODAL 2 FOR ADDING TASKS -->

 <div id="modal2" class="modal">
    <div class="modal-content">
      <h5>Add a new task</h5>
      <form action="/maple/answer/submit" method="post">{% csrf_token %}
    {{ task_form }}
          <button class="btn-small #e65100 orange darken-4 waves-effect waves-light"  type="submit" name="action">Add task

        </button>
      </form>
    </div>
    </div>


    <div id="modal3" class="modal">
       <div class="modal-content">
         <h5>Add a new task</h5>
         <form action="/maple/status/change" method="post">{% csrf_token %}
       {{ updated_status_form }}
             <button class="btn-small #e65100 orange darken-4 waves-effect waves-light"  type="submit" name="action">Change status

           </button>
         </form>
       </div>
       </div>



    <!-- ######################################################################################################## -->

<div class = "container">
  {% if success %}
    <h1>Your request has been submitted</h1>
  {% else %}

  {% endif %}

  <div class = "row">
    <div class = "col s12 m12">
      <br/>

      <a href = "/maple/data-projects/{{project.data_project.id}}"class="#"><i style="color:#ff3d00;" class="material-icons left small">arrow_back</i></a><br/>
      <h5>{{project.output_title}}</h5>
      <br/>
      <br/>


    </div>


    <div class="row">
      <div class="col m6 s6">
        <strong class="thin">Current status:</strong>
      </div>
      <div class="col m6 s6">
        {{project.current_status}}
      </div>
      </div>
      <div class = "row">

      <div class="col m6 s6">
        <strong class="thin">Data assets used in this output:</strong>
      </div>
      <div class="col m6 s6">
        {% for obj in project.data_assets.all %}
        {{ obj }}{% if forloop.last %} {% else %}, {% endif %}
        {% endfor %}
      </div>
    </div>
    <div class = "row">
      <div class="col m6 s6">
        <strong class="thin">Related documentation:</strong>
      </div>
      <div class="col m6 s6">
        {{project.related_documentation}}
      </div>
    </div>
    <div class = "row">
      <div class="col m6 s6">
        <strong class="thin">Working folder:</strong>
      </div>
      <div class="col m6 s6">
        {{project.working_folder}}
      </div>
    </div>
    <div class = "row">
      <div class="col m6 s6">
        <strong class="thin">Start date:</strong>
      </div>
      <div class="col m6 s6">
        {{project.start_date}}
      </div>
    </div>
    <div class = "row">
      <div class="col m6 s6">
        <strong class="thin">Output type:</strong>
      </div>
      <div class="col m6 s6">
        {{project.output_type}}
      </div>
    </div>
    <div class = "row">
      <div class="col m6 s6">
        <strong class="thin">Expected release date:</strong>
      </div>
      <div class="col m6 s6">
        {{project.expected_release_date}}
      </div>
    </div>
    <div class = "row">
      <div class="col m6 s6">
        <strong class="thin">PubMed ID:</strong>
      </div>
      <div class="col m6 s6">
        {{project.pubmed_id}}
      </div>
    </div>
    <div class = "row">
      <div class="col m6 s6">
        <strong class="thin">Date due:</strong>
      </div>
      <div class="col m6 s6">
        {{project.date_due}}
      </div>
    </div>


      {% if user.is_superuser %}
  <div class = "col s12 m12">
    <br/>
     <strong style="font-size: 12px">
       <a class = "modal-trigger orange-text text-darken-4" href="/admin/data_projects/dataprojectoutput/{{project.id}}">Admin</a>
     </strong>
     {% endif %}


  </div>
  </div>
<div class = "row">
        <div class="col s6 m6">
          <br/><strong>Research output summary</strong>
          <hr/>
          <div>
            {{project.summary}}
            <br/>

          </div>
</div>
          <div class = "col s6 m6">
            {% if project.requiredapproval_set.all %}
            <ul class="collapsible z-depth-0">
              <li>
                <div class="collapsible-header"><b>Approvals</b></div>

              </li>

              {%  for obj in project.requiredapproval_set.all %}

              <li>
                <div class="collapsible-header">
                  <div class = "col s8 m8">{{ obj.approval_from}}</div>
                  {% if obj.granted %}
                  <div class = "col s4 m4"> <strong class="green-text text-darken-2" style="font-size: 10px">Approved</strong></div>
                  {% else %}
                  <div class = "col s4 m4"> <strong class="red-text text-darken-2" style="font-size: 10px">Pending</strong></div>
                  {% endif %}
                <br/>
              </div>
                <div class="collapsible-body">
                  <div class = "row">
                    <div class = "thin col s4 m4">
                    Approval ID:
                    </div>
                    <div class = "col s8 m8">
                       {{ obj.approval_reference}}
                     </div>
                     <div class = "thin col s4 m4">
                     Approval contact:
                     </div>
                     <div class = "col s8 m8">
                        {{ obj.approval_contact_name}}
                      </div>
                      <div class = "thin col s4 m4">
                      Approval expiry:
                      </div>
                      <div class = "col s8 m8">
                         {{ obj.approval_end_date}}
                       </div>
                  </div>

                </div>
              </li>
              {% endfor %}

            </ul>
            {% endif %}


</div>


      </div>

    <div class = "row">
      <div class = "col s12 m12">
        <strong>Notes and Tasks</strong>
   <hr/>
      </div>
          {% if user.is_superuser %}
      <div class = "col s12 m12">
         <strong style="font-size: 12px">
           <a class = "modal-trigger orange-text text-darken-4" href="#modal1">Add note</a>
         </strong>
         {% endif %}
        </div>
      </div>


<div class = "row">
  <ul class="collection">
    {% if project.noteortask_set.all %}
     {% for obj in project.noteortask_set.all  %}
      <li class="collection-item">
       <strong class="grey-text text-darken-2" style="font-size: 11px">
         {{ obj.created_by.first_name}} {{obj.created_by.last_name}} added a {{obj.type }} on {{ obj.date_and_time_created}}
       </strong><br/>
       <div>{{obj.detail}}</div>
      {% if obj.type == "Task" %}
      <strong class="grey-text text-darken-2" style="font-size: 11px">Allocated to {{ obj.allocated_to.first_name}} {{obj.allocated_to.last_name}}, due by {{ obj.date_due}}, and
        {% if obj.task_completed == True %} has been completed. {% else %} not yet completed. {% endif %}
      </strong><br/><br/>


          {% endif %}

          {% if user.is_superuser or request.user == obj.allocated_to or request.user == obj.created_by %}

      <div>
        <strong style="font-size: 12px">
         <a href ="/maple/task-note-edit/{{obj.id}}" class = "orange-text text-darken-4">Edit</a>
        </strong>
      </div>




   {% endif %}

      </li>
  {% endfor %}
  {% else %}
  <li class="collection-item">
     <div>No tasks have been added to this request or project</div>
  </li>
 {% endif %}

    </ul>

</div>
  </div>

</div>


{% endblock %}

main/templates/main/data-project-review-detail.html
{% extends "main/base.html" %}

{% load static %}

{% block metadata %}

<div class="container">

  <div class = "row">
    <div class = "col s12 m12">
      <br/>
      <a href = "/maple/data-project-review"class="#"><i style="color:#ff3d00;" class="material-icons left small">arrow_back</i></a><br/>

    </div>
  </div>


  <div class = "row">
    <div class = "col s8 m8">


<div class = "row">
  <div class = "col s12 m12">
<h6>Grant details</h6>
<hr/>
</div>
</div>

<div class="row">
  <div class="col m6 s6">
    <strong>Related grant ID:</strong>
  </div>
    <div class="col m6 s6">
    {{ grant_review.grant_id }}
  </div>
</div>

<div class="row">
  <div class="col m6 s6">
    <strong>Grant title:</strong>
  </div>
    <div class="col m6 s6">
    {{ grant_review.application_title }}
  </div>
</div>


<div class="row">
  <div class="col m6 s6">
    <strong>Grant contact name:</strong>
  </div>
    <div class="col m6 s6">
    {{ grant_review.ci_prefix }} {{ grant_review.ci_name}}
  </div>
</div>



<div class="row">
  <div class="col m6 s6">
    <strong>Administering organisation:</strong>
  </div>
    <div class="col m6 s6">
    {{ grant_review.administering_organisation }}
  </div>
</div>


<div class="row">
  <div class="col m6 s6">
    <strong>Lead organisation:</strong>
  </div>
    <div class="col m6 s6">
    {{ grant_review.lead_organisation }}
  </div>
</div>



<div class="row">
  <div class="col m6 s6">
    <strong>Current status:</strong>
  </div>
    <div class="col m6 s6">
    {{ grant_review.status_of_review}}
  </div>
</div>


    </div>

    <div class = "col s1 m1">

    </div>

    <div class = "col s6 m6">
<br/>







    </div>
  </div>




<div class="row">


  <div class="col s12 m12">
    <br/>

    <h6>Reviews</h6>
    <div>
      <strong style="font-size: 12px">
        <a class = "modal-trigger orange-text text-darken-4" href="/admin/data_projects/dataprojectgrantapplicationreviewerscore/add/">Add new review</a>
      </strong>
    </div>
    <hr/>


        <ul class="collection">
          <li class="collection-item">
            <div class="row">
            <div class="col s2 m2"><strong class="thin">Reviewer name</strong></div>
            <div class="col s1 m1"><strong class="thin">Significance score</strong></div>
            <div class="col s1 m1"><strong class="thin">Team track record score</strong></div>
            <div class="col s1 m1"><strong class="thin">Translation score</strong></div>
              <div class="col s1 m1"><strong class="thin">sustainability score</strong></div>
            <div class="col s6 m6"><strong class="thin">Comments</strong></div>

      </li>

      </ul>
        <ul class="collection">

        {% for obj in grant_review.dataprojectgrantapplicationreviewerscore_set.all %}


            <li class="collection-item">
              <div class="row">
              <div class="col s2 m2">{{ obj.reviewer_name}} </div>
              <div class="col s1 m1">{{obj.significance_score}}</div>
              <div class="col s1 m1">  {{ obj.team_track_record_score}}</div>
              <div class="col s1 m1">{{ obj.translation_score}}</div>
              <div class="col s1 m1">{{ obj.sustainability_score}}</div>
                <div class="col s6 m6">{{ obj.comments}}</div>

              </div>
              <div>
                <strong style="font-size: 12px">
                  <a class = "modal-trigger orange-text text-darken-4" href="/admin/data_projects/dataprojectgrantapplicationreviewerscore/{{obj.id}}/change/">Edit</a>
                </strong>
              </div>
            </li>

        {% endfor %}
        </ul>

  </div>






</div>




 </div>
{% endblock %}

main/templates/main/data-requests.html
{% extends "main/base.html" %}
{% load static %}
{% load url_params_persist %}
{% block metadata %}

<div class="containesr">

<div class = "row">
  <div class = "col s1 m1">

  </div>
  <div class = "col s10 m10 right-align">

     {% if users.has_other_pages %}
       <ul class="pagination">
        {% if users.has_previous %}
          <li><a href="?{% param_replace page=users.previous_page_number %}"><i class="material-icons">chevron_left</i></a></li>
        {% else %}
         <li class="disabled"><i class="disabled-gray material-icons">chevron_left</i></li>
      {% endif %}
        {% for i in users.paginator.page_range %}
          {% if users.number == i %}
            <li class=" move-down active">&nbsp;{{ i }}&nbsp;</li>
          {% else %}
            <li><a href="?{% param_replace page=i %}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if users.has_next %}
          <li><a href="?{% param_replace page=users.next_page_number %}"><i class="material-icons">chevron_right</i></a></li>
        {% else %}
          <li class="disabled"><i class="disabled-gray material-icons">chevron_right</i></li>
        {% endif %}
      </ul>
      {% endif %}
  </div>

</div>

<div class="row">
  <div class="col s1 m1">

  </div>

  <div class="col s2 m2" xstyle="overflow-y:scroll; height:600px;">
    <br/>
      <strong>Data requests</strong>
      <br/>

    <div class="thin">
    <br/>Submit a new request <a href="/maple/submit-data-request">here</a>.
<br/>
    </div>
    <br/>
  <strong>Search requests</strong>
    <form action="" method="get">

        {{ filter.form.as_p }}
        <br/>
        <br/>
        <div class="col s6 m6">
          <button class="btn-small #e65100 orange darken-4 waves-effect waves-light"  type="submit" name="action">Filter
        </button>
        </div>
        <div class="col s6 m6">
          <a class="btn btn-small #e65100 orange darken-4 waves-effect waves-light" href="{% url 'main:data_requests' %}">Reset</a>

        </div>
    </form>

  </div>
  <div class="col s8 m8">

<input id="myInput" placeholder="Search filtered results" id="first_name" type="text" class="validate">


    <ul id="bob" class="collection">
    {% for obj in users %}




        <li class="collection-item">
          <div class="row">
          <div  class="col s2 m2">
            <strong class="thin">Date received</strong><br/>
            {{ obj.date_received}}
          </div>
            <div  class="col s2 m2">
              <strong class="thin">Request from</strong><br/>
              {{obj.requestor_contact_name}}</div>
            <div class="col s2 m2">
<strong class="thin">Date type</strong><br/>
              {{ obj.data_type}}</div>
          <div  class="col s2 m2">
<strong class="thin">Date due</strong><br/>
            {{obj.date_due}}</div>


          <div class="col s3 m3">
            <strong class="thin">Current status</strong><br/>
            {{obj.current_status}}</div>
          <div class="col s1 m1">


            <a href =  "/maple/data-requests/{{obj.id}}"class="#"><i style="color:#ff3d00;" class="material-icons small">arrow_forward</i></a>
          </div>


          </div>
          <div class="row">
            <div class = "col s8 m8">
                <strong class = "thin">Details</strong><br/>
                {{ obj.detail | truncatewords:30}}
                <br/>

                <strong class="grey-text text-darken-2" style="font-size: 10px">{{ obj.related_documentation}}</strong><br/>
            </div>
            <div  class = "col s4 m4">

              {% if obj.noteortask_set.all %}
                <strong class="thin">Tasks assigned to</strong><br/>
              {% endif %}
              {% for task in obj.noteortask_set.all %}
              	{% if task.type == "Task"  %}
              	 {% ifchanged task.allocated_to %}
              	 	{{ task.allocated_to}}
                  {% if task.task_completed %}
                  (completed),
                  {% else %}
                  (outstanding),
                  {% endif %}
              	 {% endifchanged %}
              	{% endif %}

              {% endfor %}

            </div>
          </div>
        </li>

    {% endfor %}
    </ul>
  </div>



</div>


<ul id="bob" class="collection">


 </ul>

 </div>
{% endblock %}